apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-nginx-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/your-username/your-repo
    targetRevision: HEAD
    path: my-static-app
    helm:
      valueFiles:
        - values.yaml
        - secrets://secrets.enc.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
